version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - nextjs
    volumes:
      - /home/ssl_certificates/:/etc/nginx/ssl/:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" 
    restart: unless-stopped
