version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      - NODE_ENV=production
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - NEXT_PUBLIC_GOOGLE_RECAPTURE=${NEXT_PUBLIC_GOOGLE_RECAPTURE}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - nextjs
    volumes:
      - /home/ssl_certificates/:/etc/nginx/ssl/:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" 
      - "443:443"
    restart: unless-stopped
